server:
  port: 8205

mybatis-plus:
  type-enums-package: com.zxwcbj.ccyx.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.14.186.53:45417/shequ-activity?characterEncoding=utf-8&useSSL=false
    username: root
    password: H7fMW3EVHGFEFLnSni

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
