server:
  port: 8203
# TODO
mybatis-plus:
  type-enums-package: com.zxwcbj.ccyx.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://106.14.186.53:45417/shequ-acl?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://192.168.137.28:3306/shequ-product?characterEncoding=utf-8&useSSL=false
    username: root
    password: 9BtrbJfUHNRgreqR8GtS

#  rabbitmq:
#    host: 106.14.186.53
#    port: 5672
#    username: rabbitmq
#    password: rabbitmq
#    publisher-confirm-type: CORRELATED  #发布确认模式，消息是否被成功发送到交换机
#    publisher-returns: true
#    listener:
#      simple:
#        prefetch: 1
#        concurrency: 3
#        acknowledge-mode: manual   #消费端手动确认

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#minio:
#  endpoint: http://106.14.186.53:9001
#  accessKey: PUSIhk81RbWIvdCpRmps
#  secretKey: wbX9THxtZXNPqVctSdnRCJOG1otXyJTYIVV7lNOZ
#  bucketName: buck

